name:                catlang
version:             0.1.0.0
github:              "isovector/catlang"
license:             BSD-3-Clause
author:              "Sandy Maguire"
maintainer:          "example@example.com"
copyright:           "2025 Sandy Maguire"
language: GHC2021

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/catlang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- recursion-schemes
- transformers
- mtl
- syb
- pretty
- process
- catalyst
- template-haskell
- megaparsec
- parser-combinators
- text
- monoidal-containers

default-extensions:
- DerivingStrategies
- DerivingVia
- TypeFamilies
- LambdaCase
- ViewPatterns
- PatternSynonyms


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  catlang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catlang
